# Generated by Django 5.0.1 on 2025-02-11 05:20

import django.db.models.deletion
import environments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name can only contain letters, numbers, underscores, periods, and hyphens.', max_length=100, validators=[environments.models.validate_container_name])),
                ('description', models.TextField(blank=True)),
                ('environment_type', models.CharField(choices=[('vscode', 'VSCode'), ('webtop', 'Docker Webtop'), ('custom', 'Custom Environment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(max_length=255)),
                ('ports', models.JSONField(default=dict, help_text='JSON object mapping port labels to port configurations. Example: {"web": {"port": "8080", "description": "Web Interface"}}')),
                ('subdomain', models.CharField(help_text='Base subdomain for accessing the environment (e.g., code for code-web.yourdomain.com)', max_length=63, unique=True, validators=[environments.models.validate_subdomain])),
                ('volumes', models.TextField(blank=True, help_text='One volume mount per line in host_path:container_path format')),
                ('env_vars', models.TextField(blank=True, help_text='Environment variables in KEY=value format, one per line')),
                ('cpu_limit', models.CharField(blank=True, help_text='CPU limit (e.g., 0.5, 1.0, 2.0)', max_length=10)),
                ('memory_limit', models.CharField(blank=True, help_text='Memory limit (e.g., 512m, 1g, 2g)', max_length=10)),
                ('auto_start', models.BooleanField(default=False, help_text='Start container automatically on system boot')),
                ('volume_name', models.CharField(blank=True, max_length=255)),
                ('environment_variables', models.JSONField(blank=True, default=dict, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('container_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
