# Generated by Django 5.0.1 on 2025-02-08 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('environment_type', models.CharField(choices=[('vscode', 'VSCode'), ('webtop', 'Docker Webtop')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('volume_path', models.CharField(max_length=255)),
                ('environment_variables', models.JSONField(default=dict)),
                ('is_running', models.BooleanField(default=False)),
                ('container_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
