# Generated by Django 5.0.1 on 2025-02-08 16:12

import environments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_remove_environment_volume_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(help_text='Name can only contain letters, numbers, underscores, periods, and hyphens.', max_length=100, validators=[environments.models.validate_container_name]),
        ),
    ]
