# Generated by Django 5.0.1 on 2025-02-08 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0003_alter_environment_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('name', 'created_by')},
        ),
    ]
