# Generated by Django 5.0.1 on 2025-02-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_remove_environment_port_environment_auto_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='environment_type',
            field=models.CharField(choices=[('vscode', 'VSCode'), ('webtop', 'Docker Webtop'), ('custom', 'Custom Environment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='environment',
            name='environment_variables',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
